
version: '2'

services:
  nats-flows:
    image: akawato2018/mainflows:2.7
    network_mode: host
    restart: ${RESTART}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
