.catalog:
  name: main flows private test
  version: 2.2
  uuid: mainflows-0
  questions:
  - variable: RESTART
    description: 'Application restart option: always, on-failure'
    label: 'Restart:'
    required: true
    default: "always"
    type: string
