version: '2'

services:
  nats-flows:
    image: akawato2018/webst:0.1
    ports:
      - 9090:9090
    links:
      - nats
    networks:
      - backend
   nats:
     image: akawato2018/nats-server:latest
     networks:
       - backend
 networks:
   backend:
     driver: "bridge"
       
    
