.catalog:
  name: load status private test
  version: publish
  uuid: loader-webapp:publish
  questions:
  - variable: RESTART
    description: 'Application restart option: always, on-failure'
    label: 'Restart:'
    required: true
    default: "always"
    type: string
